/*
 * CLI Help Text Catalog
 * ---------------------
 * Defines the static help entries shown by Aleph3 interactive consumers.
 * This header owns the plain-language descriptions for user-facing symbolic
 * functions, syntax forms, constants, and pack entries.
 */

#pragma once

#include <string>
#include <vector>

namespace aleph3 {

    struct HelpEntry {
        std::string name;
        std::string description;
        std::string category;
        std::vector<std::string> forms;
        std::vector<std::string> examples;
        std::string exactness;
        std::string unsupported;
        std::string owning_component;
        std::string manual_anchor;
    };

    inline const std::vector<HelpEntry>& get_help_entries() {
        static const std::vector<HelpEntry> entries = {
            // Arithmetic and elementary functions
            {"Plus", "Add two or more expressions.", "Arithmetic",
                {"Plus[a, b, ...]", "a + b"}, {"2 + 3 -> 5", "1/2 + 1/3 -> 5/6"},
                "Exact integers and rationals stay exact unless an approximate input participates.",
                "List behavior is limited to documented finite elementwise cases; broad Listable semantics are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Minus", "Subtract one expression from another.", "Arithmetic",
                {"Minus[a, b]", "a - b"}, {"8 - 3 -> 5", "x - 1 -> x - 1"},
                "Exact integers and rationals stay exact unless an approximate input participates.",
                "Only binary subtraction is supported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Times", "Multiply two or more expressions.", "Arithmetic",
                {"Times[a, b, ...]", "a * b"}, {"4 * 5 -> 20", "1/2 * x -> 1/2 * x"},
                "Exact integers and rationals stay exact unless an approximate input participates.",
                "List behavior is limited to documented finite elementwise cases; broad tensor semantics are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Divide", "Divide one expression by another.", "Arithmetic",
                {"Divide[a, b]", "a / b"}, {"8 / 4 -> 2", "1/2 / 1/3 -> 3/2"},
                "Exact rational division stays exact for supported integer and rational inputs.",
                "Division by zero is diagnosed in strict runtime contexts; broad rational-expression cancellation is deferred.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Power", "Raise an expression to a power.", "Arithmetic",
                {"Power[a, b]", "a^b"}, {"2^5 -> 32", "x^2 -> x^2"},
                "Exact and numeric powers use the current arithmetic and simplification contracts.",
                "Branch-sensitive power laws and broad symbolic exponent reasoning are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Negate", "Unary numeric negation used by parsed prefix minus.", "Arithmetic",
                {"Negate[x]", "-x"}, {"-4 -> -4", "-x -> -1 * x"},
                "Exact integer-like inputs and symbolic negation follow the shared arithmetic path.",
                "This is an implementation-facing head; broad user-facing unary operator help remains through syntax examples.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Clamp", "Clamp a numeric value between numeric lower and upper bounds.", "Arithmetic",
                {"Clamp[x, low, high]"}, {"Clamp[12, 0, 10] -> 10"},
                "Machine-real numeric inputs produce machine-real results.",
                "Non-numeric bounds and lower bounds greater than upper bounds are rejected in strict runtime contexts.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Abs", "Absolute value.", "Arithmetic",
                {"Abs[x]"}, {"Abs[-4] -> 4", "Refine[Abs[x], x >= 0] -> x"},
                "Exact numeric and assumption-backed sign cases can simplify exactly.",
                "General inequality solving and complex absolute values are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Sqrt", "Square root.", "Arithmetic",
                {"Sqrt[x]"}, {"Sqrt[9] -> 3", "Refine[Sqrt[x^2], x >= 0] -> x"},
                "Numeric inputs use machine-real evaluation; selected assumption-backed forms can simplify.",
                "Negative numeric inputs report a numeric-domain diagnostic in strict mode; broad branch analysis is unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Floor", "Greatest integer less than or equal to a numeric value.", "Arithmetic",
                {"Floor[x]"}, {"Floor[1.8] -> 1"},
                "Numeric inputs use machine-real rounding.",
                "Symbolic rounding and integer-assumption simplification are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Ceil", "Alias for Ceiling.", "Arithmetic",
                {"Ceil[x]"}, {"Ceil[1.2] -> 2"},
                "Numeric inputs use machine-real rounding.",
                "Symbolic rounding and integer-assumption simplification are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Ceiling", "Smallest integer greater than or equal to a numeric value.", "Arithmetic",
                {"Ceiling[x]"}, {"Ceiling[1.2] -> 2"},
                "Numeric inputs use machine-real rounding.",
                "Symbolic rounding and integer-assumption simplification are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Round", "Round a numeric value to the nearest integer.", "Arithmetic",
                {"Round[x]"}, {"Round[1.6] -> 2"},
                "Numeric inputs use machine-real rounding.",
                "Symbolic rounding and tie-mode customization are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Rational", "Exact rational value represented by numerator and denominator.", "Arithmetic",
                {"Rational[n, d]", "n/d"}, {"1/2 + 1/3 -> 5/6"},
                "Exact rational arithmetic stays exact until mixed with approximate numbers or N is requested.",
                "Denominator zero is invalid; arbitrary-precision rational arithmetic is deferred.",
                "syntax", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},

            // Trigonometric and hyperbolic functions
            {"Sin", "Sine of an angle in radians.", "Trigonometric",
                {"Sin[x]"}, {"Sin[0] -> 0", "Sin[x] -> Sin[x]"},
                "Known exact angles may reduce to machine-real constants; symbolic inputs are preserved.",
                "General trigonometric simplification and branch analysis are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Cos", "Cosine of an angle in radians.", "Trigonometric",
                {"Cos[x]"}, {"Cos[0] -> 1", "Cos[x] -> Cos[x]"},
                "Known exact angles may reduce to machine-real constants; symbolic inputs are preserved.",
                "General trigonometric simplification and branch analysis are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Tan", "Tangent of an angle in radians.", "Trigonometric",
                {"Tan[x]"}, {"Tan[0] -> 0", "Tan[x] -> Tan[x]"},
                "Known exact angles may reduce to machine-real constants; symbolic inputs are preserved.",
                "Poles and general trigonometric simplification are outside the supported subset.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"ArcSin", "Inverse sine.", "Trigonometric",
                {"ArcSin[x]"}, {"ArcSin[0] -> 0", "ArcSin[x] -> ArcSin[x]"},
                "Numeric inputs use machine-real evaluation when the real-domain check succeeds.",
                "Inputs outside the supported real domain report a numeric-domain diagnostic in strict mode.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"ArcCos", "Inverse cosine.", "Trigonometric",
                {"ArcCos[x]"}, {"ArcCos[1] -> 0", "ArcCos[x] -> ArcCos[x]"},
                "Numeric inputs use machine-real evaluation when the real-domain check succeeds.",
                "Inputs outside the supported real domain report a numeric-domain diagnostic in strict mode.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"ArcTan", "Inverse tangent, with a two-argument atan2 form.", "Trigonometric",
                {"ArcTan[x]", "ArcTan[x, y]"}, {"ArcTan[0] -> 0", "ArcTan[1, 1] -> 0.785398"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "No branch-cut analysis or exact symbolic arctangent identities are implemented.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"ArcSec", "Inverse secant.", "Trigonometric",
                {"ArcSec[x]"}, {"ArcSec[1] -> 0", "ArcSec[x] -> ArcSec[x]"},
                "Numeric inputs use machine-real evaluation when the real-domain check succeeds.",
                "Inputs with absolute value below one report a numeric-domain diagnostic in strict mode.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"ArcCsc", "Inverse cosecant.", "Trigonometric",
                {"ArcCsc[x]"}, {"ArcCsc[1] -> 1.570796", "ArcCsc[x] -> ArcCsc[x]"},
                "Numeric inputs use machine-real evaluation when the real-domain check succeeds.",
                "Inputs with absolute value below one report a numeric-domain diagnostic in strict mode.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"ArcCot", "Inverse cotangent.", "Trigonometric",
                {"ArcCot[x]"}, {"ArcCot[1] -> 0.785398", "ArcCot[x] -> ArcCot[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "No branch-cut analysis or exact symbolic arccotangent identities are implemented.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Csc", "Reciprocal sine.", "Trigonometric",
                {"Csc[x]"}, {"Csc[Pi/2] -> 1", "Csc[x] -> Csc[x]"},
                "Known exact angles may reduce to machine-real constants; symbolic inputs are preserved.",
                "Pole analysis and broad trigonometric simplification are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Sec", "Reciprocal cosine.", "Trigonometric",
                {"Sec[x]"}, {"Sec[0] -> 1", "Sec[x] -> Sec[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Pole analysis and broad trigonometric simplification are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Cot", "Reciprocal tangent.", "Trigonometric",
                {"Cot[x]"}, {"Cot[Pi/4] -> 1", "Cot[x] -> Cot[x]"},
                "Known exact angles may reduce to machine-real constants; symbolic inputs are preserved.",
                "Pole analysis and broad trigonometric simplification are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Sinc", "Normalized sinc function sin(x)/x with Sinc[0] = 1.", "Trigonometric",
                {"Sinc[x]"}, {"Sinc[0] -> 1", "Sinc[x] -> Sinc[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Only the normalized convention is exposed; no transform-specific sinc conventions are implemented.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Sinh", "Hyperbolic sine.", "Hyperbolic",
                {"Sinh[x]"}, {"Sinh[0] -> 0", "Sinh[x] -> Sinh[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Broad hyperbolic identities and branch analysis are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Cosh", "Hyperbolic cosine.", "Hyperbolic",
                {"Cosh[x]"}, {"Cosh[0] -> 1", "Cosh[x] -> Cosh[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Broad hyperbolic identities and branch analysis are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Tanh", "Hyperbolic tangent.", "Hyperbolic",
                {"Tanh[x]"}, {"Tanh[0] -> 0", "Tanh[x] -> Tanh[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Broad hyperbolic identities and branch analysis are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Coth", "Hyperbolic cotangent.", "Hyperbolic",
                {"Coth[x]"}, {"Coth[1] -> 1.313035", "Coth[x] -> Coth[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Pole analysis and broad hyperbolic identities are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Sech", "Hyperbolic secant.", "Hyperbolic",
                {"Sech[x]"}, {"Sech[0] -> 1", "Sech[x] -> Sech[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Broad hyperbolic identities and branch analysis are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
            {"Csch", "Hyperbolic cosecant.", "Hyperbolic",
                {"Csch[x]"}, {"Csch[1] -> 0.850918", "Csch[x] -> Csch[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Pole analysis and broad hyperbolic identities are unsupported.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},

            // Exponential, logarithmic, and other numeric functions
            {"Exp", "Exponential function.", "Exponential/Logarithmic",
                {"Exp[x]"}, {"Exp[0] -> 1", "Exp[x] -> Exp[x]"},
                "Numeric inputs use machine-real evaluation; symbolic inputs are preserved.",
                "Broad exponential identities and branch analysis are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Ln", "Natural logarithm.", "Exponential/Logarithmic",
                {"Ln[x]"}, {"Ln[E] -> 1", "Ln[x] -> Ln[x]"},
                "Numeric inputs use machine-real evaluation when the real-domain check succeeds.",
                "Nonpositive numeric inputs report a numeric-domain diagnostic in strict mode.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Log", "Natural logarithm or logarithm with an explicit base.", "Exponential/Logarithmic",
                {"Log[x]", "Log[base, x]"}, {"Log[E] -> 1", "Log[2, 8] -> 3"},
                "Numeric inputs use machine-real evaluation when the real-domain check succeeds.",
                "Nonpositive inputs, base one, and unsupported symbolic logarithm identities are outside the current subset.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},
            {"Gamma", "Gamma function.", "Other",
                {"Gamma[x]"}, {"Gamma[5] -> 24", "Gamma[x] -> Gamma[x]"},
                "Positive numeric inputs use machine-real evaluation; selected integer cases simplify.",
                "Poles, analytic continuation, and broad special-function identities are unsupported.",
                "builtin", "manual/built-in-functions.md#arithmetic-and-elementary-functions"},

            // Rewriting, rules, session state, assumptions, and inspection
            {"Replace", "Apply one supported rewrite rule through the existing whole-expression traversal.", "Symbolic",
                {"Replace[expr, rule]", "Replace[expr, rule, level]"},
                {"Replace[f[x], f[a_] -> g[a]] -> g[x]"},
                "Preserves exact expressions unless the replacement rule introduces approximate values.",
                "Rule lists and RuleDelayed are unsupported in the current replacement surface.",
                "builtin", "manual/rewriting-and-assumptions.md#rules-and-patterns"},
            {"ReplaceAll", "Alias for Replace[expr, rule] using the same whole-expression traversal.", "Symbolic",
                {"ReplaceAll[expr, rule]", "expr /. rule"},
                {"f[x] /. x -> y -> f[y]"},
                "Preserves exact expressions unless the replacement rule introduces approximate values.",
                "Rule lists and RuleDelayed are unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#rules-and-patterns"},
            {"ReplaceRepeated", "Reapply a rule until no change occurs or the fixed rewrite budget is reached.", "Symbolic",
                {"ReplaceRepeated[expr, rule]", "ReplaceRepeated[expr, rule, level]"},
                {"ReplaceRepeated[f[f[x]], f[a_] -> a, 0] -> x"},
                "Preserves exact expressions unless the replacement rule introduces approximate values.",
                "Rule lists, RuleDelayed, negative levels, and unbounded rewriting are unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#repeated-and-conditional-rewriting"},
            {"MatchQ", "Test whether an expression matches a supported symbolic pattern.", "Symbolic",
                {"MatchQ[expr, pattern]"}, {"MatchQ[f[x, x], f[a_, a_]] -> True", "MatchQ[3, _Integer] -> True"},
                "Pattern matching is structural and preserves exact values.",
                "Sequence patterns, arbitrary predicates, and broad Mathematica pattern semantics are unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#rules-and-patterns"},
            {"Rule", "Build a rewrite rule from a left-hand side to a right-hand side.", "Symbolic",
                {"lhs -> rhs"}, {"f[x] /. x -> y -> f[y]"},
                "Rules preserve exact values until a consumer applies them.",
                "Rule lists and delayed rule evaluation are outside the current replacement surface.",
                "syntax", "manual/rewriting-and-assumptions.md#rules-and-patterns"},
            {"RuleDelayed", "Reserved replacement form; not supported by the current evaluator.", "Symbolic",
                {"lhs :> rhs"}, {},
                "No evaluation contract is exposed for delayed rules yet.",
                "RuleDelayed is not accepted by Replace, ReplaceAll, or ReplaceRepeated.",
                "syntax", "manual/rewriting-and-assumptions.md#rules-and-patterns"},
            {"Set", "Assign a session-local own value.", "Symbolic",
                {"name = expr"}, {"a = 2", "a + 3 -> 5"},
                "Stores the evaluated right-hand side in the active session.",
                "Provider-owned names still keep provider precedence.",
                "session", "manual/sessions-cli-and-notebook.md#cli-workflow"},
            {"SetDelayed", "Define a session-local user function evaluated when it is called.", "Symbolic",
                {"f[x_] := expr"}, {"f[x_] := x + 1", "f[4] -> 5"},
                "The delayed body is evaluated when the user function is called.",
                "Only the bounded user-definition subset is supported.",
                "session", "manual/sessions-cli-and-notebook.md#cli-workflow"},
            {"Clear", "Remove a session-local own value and user function definition.", "Symbolic",
                {"Clear[symbol]"}, {"a = 10", "Clear[a]", "a -> a"},
                "Cleanup affects only session-local definition state.",
                "Clear cannot remove builtin, special-form, pack, or host-owned behavior.",
                "builtin", "manual/sessions-cli-and-notebook.md#cli-workflow"},
            {"Unset", "Remove a session-local own value only.", "Symbolic",
                {"Unset[symbol]"}, {"a = 10", "Unset[a]", "a -> a"},
                "Cleanup affects only session-local own-value state.",
                "Unset does not remove user function definitions in this MVP slice.",
                "builtin", "manual/sessions-cli-and-notebook.md#cli-workflow"},
            {"FreeVariables", "List symbols that occur free in an unevaluated expression.", "Symbolic",
                {"FreeVariables[expr]"}, {"FreeVariables[f[a_] -> g[a, y]] -> {y}"},
                "This is structural inspection; it does not evaluate or mutate the expression.",
                "Only current pattern and function-definition binders are recognized.",
                "builtin", "manual/rewriting-and-assumptions.md#variable-dependency-inspection"},
            {"BoundVariables", "List pattern or function-definition variables bound in an expression.", "Symbolic",
                {"BoundVariables[expr]"}, {"BoundVariables[f[a_] -> g[a, y]] -> {a}"},
                "This is structural inspection; it does not evaluate or mutate the expression.",
                "Future binders such as Sum, Product, or With are not part of the current surface.",
                "builtin", "manual/rewriting-and-assumptions.md#variable-dependency-inspection"},
            {"DependsOn", "Test whether an expression has a symbol as a free variable.", "Symbolic",
                {"DependsOn[expr, x]"}, {"DependsOn[f[a_] -> g[a, y], a] -> False", "DependsOn[f[a_] -> g[a, y], y] -> True"},
                "This is structural inspection; it does not evaluate or mutate the expression.",
                "The second argument must be a symbol; broad semantic dependency analysis is unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#variable-dependency-inspection"},
            {"Assuming", "Evaluate an expression with temporary boolean, sign, or domain facts.", "Symbolic",
                {"Assuming[assumptions, expr]"}, {"Assuming[x > 0, If[x > 0, 1, 2]] -> 1"},
                "Facts are scoped to the evaluation and do not leak into the session.",
                "Contradictory direct facts fail atomically; this is not a general theorem prover.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},
            {"Refine", "Simplify an expression using temporary boolean, sign, or domain facts.", "Symbolic",
                {"Refine[expr]", "Refine[expr, assumptions]"}, {"Refine[Sqrt[x^2], x >= 0] -> x"},
                "Exact simplifications use the supported assumption query surface.",
                "General inequality solving and broad branch-sensitive simplification are unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},
            {"Positive", "Test whether a value is known to be greater than zero.", "Symbolic",
                {"Positive[x]"}, {"Positive[3] -> True", "Refine[Positive[x], x > 0] -> True"},
                "Answers use supported exact values and direct assumption facts.",
                "Unknown facts remain unevaluated; general inequality proving is unsupported.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"Negative", "Test whether a value is known to be less than zero.", "Symbolic",
                {"Negative[x]"}, {"Negative[-2] -> True"},
                "Answers use supported exact values and direct assumption facts.",
                "Unknown facts remain unevaluated; general inequality proving is unsupported.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"NonNegative", "Test whether a value is known to be greater than or equal to zero.", "Symbolic",
                {"NonNegative[x]"}, {"NonNegative[0] -> True"},
                "Answers use supported exact values and direct assumption facts.",
                "Unknown facts remain unevaluated; general inequality proving is unsupported.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"NonPositive", "Test whether a value is known to be less than or equal to zero.", "Symbolic",
                {"NonPositive[x]"}, {"NonPositive[0] -> True"},
                "Answers use supported exact values and direct assumption facts.",
                "Unknown facts remain unevaluated; general inequality proving is unsupported.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"ZeroQ", "Test whether a value is known to be exactly zero.", "Symbolic",
                {"ZeroQ[x]"}, {"ZeroQ[0] -> True"},
                "Answers use supported exact values and direct assumption facts.",
                "Unknown facts remain unevaluated; broad simplification to prove zero is unsupported.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"NonZeroQ", "Test whether a value is known to be nonzero.", "Symbolic",
                {"NonZeroQ[x]"}, {"NonZeroQ[1] -> True", "Refine[NonZeroQ[x], x != 0] -> True"},
                "Answers use supported exact values and direct assumption facts.",
                "Unknown facts remain unevaluated; broad simplification to prove nonzero is unsupported.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"IntegerQ", "Test whether a value is known to be an integer.", "Symbolic",
                {"IntegerQ[x]"}, {"IntegerQ[3] -> True"},
                "Answers use supported exact values and direct domain facts.",
                "Unknown symbolic domains remain unevaluated unless supported assumptions prove them.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"RationalQ", "Test whether a value is known to be an exact rational.", "Symbolic",
                {"RationalQ[x]"}, {"RationalQ[1/2] -> True"},
                "Answers use supported exact rational values and direct domain facts.",
                "Decimal approximate numbers are not exact rationals.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},
            {"RealQ", "Test whether a value is known to be real.", "Symbolic",
                {"RealQ[x]"}, {"RealQ[1/2] -> True"},
                "Answers use supported numeric values and direct domain facts.",
                "Unknown symbolic domains remain unevaluated unless supported assumptions prove them.",
                "builtin", "manual/built-in-functions.md#symbolic-predicates"},

            // Comparisons and conditionals
            {"If", "Evaluate one of two branches according to a boolean condition.", "Logical",
                {"If[condition, then, else]"}, {"If[3 < 4, \"yes\", \"no\"] -> \"yes\""},
                "The selected branch is evaluated; the unselected branch remains held.",
                "The condition must evaluate to True or False in strict runtime contexts.",
                "builtin", "manual/built-in-functions.md#logic-and-conditional-evaluation"},
            {"And", "Logical conjunction with held, short-circuit evaluation.", "Logical",
                {"And[a, b, ...]"}, {"And[True, True] -> True", "And[False, x] -> False"},
                "Concrete boolean prefixes reduce deterministically.",
                "Unknown non-boolean arguments are preserved; this is not a theorem prover.",
                "builtin", "manual/built-in-functions.md#logic-and-conditional-evaluation"},
            {"Or", "Logical disjunction with held, short-circuit evaluation.", "Logical",
                {"Or[a, b, ...]"}, {"Or[False, True] -> True", "Or[True, x] -> True"},
                "Concrete boolean prefixes reduce deterministically.",
                "Unknown non-boolean arguments are preserved; this is not a theorem prover.",
                "builtin", "manual/built-in-functions.md#logic-and-conditional-evaluation"},
            {"Equal", "Test supported comparable values for equality.", "Logical",
                {"Equal[a, b]", "a == b"}, {"Equal[1/2, 2/4] -> True"},
                "Exact rationals, numbers, booleans, and strings compare within supported paths.",
                "General symbolic equality proving is unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},
            {"NotEqual", "Test supported comparable values for inequality.", "Logical",
                {"NotEqual[a, b]", "a != b"}, {"NotEqual[1, 2] -> True"},
                "Exact rationals, numbers, booleans, and strings compare within supported paths.",
                "General symbolic disequality proving is unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},
            {"Less", "Test whether one supported numeric value is less than another.", "Logical",
                {"Less[a, b]", "a < b"}, {"Less[1, 2] -> True"},
                "Exact rational and numeric comparisons are supported.",
                "General inequality solving is unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},
            {"Greater", "Test whether one supported numeric value is greater than another.", "Logical",
                {"Greater[a, b]", "a > b"}, {"Greater[2, 1] -> True"},
                "Exact rational and numeric comparisons are supported.",
                "General inequality solving is unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},
            {"LessEqual", "Test whether one supported numeric value is less than or equal to another.", "Logical",
                {"LessEqual[a, b]", "a <= b"}, {"LessEqual[2, 2] -> True"},
                "Exact rational and numeric comparisons are supported.",
                "General inequality solving is unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},
            {"GreaterEqual", "Test whether one supported numeric value is greater than or equal to another.", "Logical",
                {"GreaterEqual[a, b]", "a >= b"}, {"GreaterEqual[2, 2] -> True"},
                "Exact rational and numeric comparisons are supported.",
                "General inequality solving is unsupported.",
                "builtin", "manual/rewriting-and-assumptions.md#assumptions-and-refine"},

            // Strings, lists, and structural output
            {"StringJoin", "Concatenate strings.", "String",
                {"StringJoin[str1, str2, ...]"}, {"StringJoin[\"aleph\", \"3\"] -> \"aleph3\""},
                "String operations preserve exact symbolic values outside their string results.",
                "All arguments must be strings.",
                "builtin", "manual/built-in-functions.md#strings-and-lists"},
            {"StringLength", "Return the length of a string.", "String",
                {"StringLength[str]"}, {"StringLength[\"aleph3\"] -> 6"},
                "The length is returned as the current integer-like Number value.",
                "The argument must be a string.",
                "builtin", "manual/built-in-functions.md#strings-and-lists"},
            {"StringReplace", "Replace literal string substrings using a string-to-string rule.", "String",
                {"StringReplace[str, \"from\" -> \"to\"]"}, {"StringReplace[\"abcabc\", \"abc\" -> \"x\"] -> \"xx\""},
                "String operations preserve exact symbolic values outside their string results.",
                "Only a single literal string rule is supported; rule lists and patterns are unsupported.",
                "builtin", "manual/built-in-functions.md#strings-and-lists"},
            {"StringTake", "Take a substring by count or one-based inclusive range.", "String",
                {"StringTake[str, n]", "StringTake[str, {start, end}]"}, {"StringTake[\"Hello\", {2, 4}] -> \"ell\""},
                "The result is an exact string value.",
                "Indexes must be valid concrete integers inside the string bounds.",
                "builtin", "manual/built-in-functions.md#strings-and-lists"},
            {"List", "Finite expression container written with braces.", "List",
                {"{a, b, c}", "List[a, b, c]"}, {"Length[{a, b, c}] -> 3"},
                "List elements preserve their existing exactness.",
                "Lazy sequences, sequence patterns, and implicit Listable behavior are unsupported.",
                "syntax", "manual/built-in-functions.md#strings-and-lists"},
            {"Length", "Return the number of elements in a list.", "List",
                {"Length[list]"}, {"Length[{a, b, c}] -> 3"},
                "The length is returned as the current integer-like Number value.",
                "Only explicit finite lists are accepted.",
                "builtin", "manual/built-in-functions.md#strings-and-lists"},
            {"Head", "Return the public symbolic head of an evaluated expression.", "List",
                {"Head[expr]"}, {"Head[{a, b}] -> List", "Head[1/2] -> Rational"},
                "The returned head is an ordinary symbol.",
                "This is structural inspection, not reflection over private C++ types.",
                "builtin", "manual/built-in-functions.md#structural-inspection-and-finite-list-transforms"},
            {"Part", "Extract a one-based part from a list, call, or rule.", "List",
                {"Part[expr, index]"}, {"Part[{a, b, c}, 2] -> b", "Part[x -> y, 2] -> y"},
                "Extracted values preserve their existing exactness.",
                "Nested Part, levels, heads traversal, invalid indexes, and atomic extraction are unsupported.",
                "builtin", "manual/built-in-functions.md#structural-inspection-and-finite-list-transforms"},
            {"Map", "Apply a symbol head to each element of an explicit finite list.", "List",
                {"Map[f, list]"}, {"Map[f, {a, b, c}] -> {f[a], f[b], f[c]}"},
                "Elements preserve their existing exactness unless the mapped head evaluates them otherwise.",
                "Only explicit finite lists and symbol heads are supported.",
                "builtin", "manual/built-in-functions.md#structural-inspection-and-finite-list-transforms"},
            {"Apply", "Replace the list head with a symbol head.", "List",
                {"Apply[f, list]"}, {"Apply[f, {a, b}] -> f[a, b]"},
                "Elements preserve their existing exactness unless the applied head evaluates them otherwise.",
                "Only explicit finite lists and symbol heads are supported.",
                "builtin", "manual/built-in-functions.md#structural-inspection-and-finite-list-transforms"},
            {"Select", "Keep finite-list elements accepted by a predicate.", "List",
                {"Select[list, predicate]"}, {"Select[{1, x, 2}, IntegerQ] -> {1, 2}"},
                "Selected elements preserve their existing exactness.",
                "The predicate must resolve to True, False, or an unresolved predicate call; broad truthiness is unsupported.",
                "builtin", "manual/built-in-functions.md#structural-inspection-and-finite-list-transforms"},
            {"Cases", "Return finite-list elements matching a supported pattern.", "List",
                {"Cases[list, pattern]"}, {"Cases[{x, 1, y}, _Symbol] -> {x, y}"},
                "Matched elements preserve their existing exactness.",
                "Only explicit finite lists and the current pattern subset are supported.",
                "builtin", "manual/built-in-functions.md#structural-inspection-and-finite-list-transforms"},
            {"N", "Request numeric evaluation where supported.", "Numeric",
                {"N[expr]"}, {"N[1/2] -> 0.5", "N[Pi] -> 3.141593"},
                "Exact integers and rationals remain exact until N or machine-real inputs request approximation.",
                "Arbitrary precision and broad numerical analysis are deferred.",
                "builtin", "manual/built-in-functions.md#numeric-and-structural-output"},
            {"FullForm", "Show the internal expression structure.", "Other",
                {"FullForm[expr]"}, {"FullForm[x + 1] -> \"Plus[x, 1]\""},
                "FullForm returns an exact string containing the evaluated expression structure.",
                "It is diagnostic text, not a stable serialization format.",
                "builtin", "manual/built-in-functions.md#numeric-and-structural-output"},

            // Algebra pack
            {"Expand", "Expand products and powers in the current polynomial subset.", "Polynomial",
                {"Expand[expr]"}, {"Expand[(x + 1)*(x + 2)] -> x^2 + 3 * x + 2"},
                "Preserves exact integer and rational coefficients in supported polynomial inputs.",
                "Unsupported symbolic structures are preserved or rejected according to the algebra subset; this is not broad expansion.",
                "core-algebra", "manual/packs-algebra.md#expand-and-collect"},
            {"Factor", "Factor a supported exact polynomial expression.", "Polynomial",
                {"Factor[expr]"}, {"Factor[x^2 - 1] -> (x - 1) * (x + 1)"},
                "Preserves exact integer and rational polynomial coefficients.",
                "Broad transcendental and general multivariate factorization remain unsupported.",
                "core-algebra", "manual/packs-algebra.md#factor"},
            {"Collect", "Collect polynomial terms by one explicit variable selector.", "Polynomial",
                {"Collect[expr, x]", "Collect[expr, {x, y}]"}, {"Collect[y*x + x^2 + z*x, x] -> x^2 + x * y + x * z"},
                "Preserves exact integer and rational coefficients in supported polynomial inputs.",
                "Collect returns a canonical expression, not a coefficient map; symbolic coefficients are unsupported.",
                "core-algebra", "manual/packs-algebra.md#expand-and-collect"},
            {"GCD", "Compute polynomial GCD for the current supported selector forms.", "Polynomial",
                {"GCD[a, b]", "GCD[a, b, x]", "GCD[a, b, {x, y}]"},
                {"GCD[x^2 - 1, x - 1, x] -> x - 1", "GCD[x*y + x, x, {x, y}] -> x"},
                "Preserves exact integer and rational coefficients where the GCD subset supports them.",
                "General multivariate GCD, decimal coefficients, and GCD[0, 0] are unsupported or invalid.",
                "core-algebra", "manual/packs-algebra.md#polynomial-gcd"},
            {"PolynomialQuotient", "Return polynomial quotient and remainder for the current supported subset.", "Polynomial",
                {"PolynomialQuotient[a, b]", "PolynomialQuotient[a, b, x]", "PolynomialQuotient[a, b, {x, y}]"},
                {"PolynomialQuotient[x^2 + 1, x + 1, x] -> {x - 1, 2}"},
                "Preserves exact integer and rational coefficients where the division subset supports them.",
                "Division by zero, decimal multivariate division, multiple divisors, and configurable orders are unsupported.",
                "core-algebra", "manual/packs-algebra.md#quotient-and-remainder"},
            {"MatrixAdd", "Add exact dense matrices of equal shape.", "Matrix",
                {"MatrixAdd[a, b]"}, {"MatrixAdd[{{1, 1/2}}, {{4, 1/2}}] -> {{5, 1}}"},
                "Matrix entries must be exact integers or rationals.",
                "Ragged, empty, symbolic, decimal, complex, sparse, and oversized matrices are unsupported.",
                "core-algebra", "manual/packs-algebra.md#exact-dense-matrices"},
            {"MatrixMultiply", "Multiply compatible exact dense matrices.", "Matrix",
                {"MatrixMultiply[a, b]"}, {"MatrixMultiply[{{1, 2, 3}}, {{1}, {0}, {2}}] -> {{7}}"},
                "Matrix entries must be exact integers or rationals.",
                "Incompatible shapes, symbolic entries, decimal entries, and oversized results are unsupported.",
                "core-algebra", "manual/packs-algebra.md#exact-dense-matrices"},
            {"IdentityMatrix", "Construct a bounded exact identity matrix.", "Matrix",
                {"IdentityMatrix[n]"}, {"IdentityMatrix[2] -> {{1, 0}, {0, 1}}"},
                "Entries are exact integers.",
                "The size must be an integer from 1 through 64.",
                "core-algebra", "manual/packs-algebra.md#exact-dense-matrices"},
            {"Transpose", "Transpose an exact dense matrix.", "Matrix",
                {"Transpose[a]"}, {"Transpose[{{1, 2, 3}, {4, 5, 6}}] -> {{1, 4}, {2, 5}, {3, 6}}"},
                "Matrix entries must be exact integers or rationals.",
                "Ragged, empty, symbolic, decimal, complex, sparse, and oversized matrices are unsupported.",
                "core-algebra", "manual/packs-algebra.md#exact-dense-matrices"},
            {"Det", "Compute an exact dense determinant.", "Matrix",
                {"Det[a]"}, {"Det[{{1, 2}, {3, 4}}] -> -2"},
                "Matrix entries must be exact integers or rationals.",
                "Only non-empty square dense matrices inside the size budget are supported.",
                "core-algebra", "manual/packs-algebra.md#exact-dense-matrices"},
            {"RowReduce", "Compute exact reduced row-echelon form.", "Matrix",
                {"RowReduce[a]"}, {"RowReduce[{{1, 2}, {3, 4}}] -> {{1, 0}, {0, 1}}"},
                "Matrix entries must be exact integers or rationals.",
                "Ragged, empty, symbolic, decimal, complex, sparse, and oversized matrices are unsupported.",
                "core-algebra", "manual/packs-algebra.md#exact-dense-matrices"},
            {"LinearSolve", "Solve a square exact system with one unique solution.", "Matrix",
                {"LinearSolve[a, b]"}, {"LinearSolve[{{2, 1}, {1, -1}}, {5, 1}] -> {2, 1}"},
                "Matrix and vector entries must be exact integers or rationals.",
                "Non-square systems, mismatched vector lengths, singular systems, and approximate entries are unsupported.",
                "core-algebra", "manual/packs-algebra.md#exact-dense-matrices"},

            // Calculus pack
            {"D", "Differentiate an expression with respect to a symbol in the focused calculus subset.", "Calculus",
                {"D[expr, x]"}, {"D[x^2 + 3*x, x] -> 2 * x + 3"},
                "Exact polynomial-style results stay exact.",
                "Higher-order, broad partial-derivative, and general calculus workflows are outside this slice.",
                "core-calculus", "manual/packs-calculus.md#differentiation"},
            {"Differentiate", "Long-form alias for D[expr, x].", "Calculus",
                {"Differentiate[expr, x]"}, {"Differentiate[x^2, x] -> 2 * x"},
                "Exact polynomial-style results stay exact.",
                "Higher-order, broad partial-derivative, and general calculus workflows are outside this slice.",
                "core-calculus", "manual/packs-calculus.md#differentiation"},

            // Constants
            {"Pi", "The mathematical constant pi.", "Constants",
                {"Pi"}, {"N[Pi] -> 3.141593"},
                "Symbolic Pi remains exact as a named constant until numeric evaluation is requested.",
                "No arbitrary-precision constant evaluation is implemented.",
                "builtin", "manual/built-in-functions.md#numeric-and-structural-output"},
            {"E", "The mathematical constant e.", "Constants",
                {"E"}, {"N[E] -> 2.718282"},
                "Symbolic E remains exact as a named constant until numeric evaluation is requested.",
                "No arbitrary-precision constant evaluation is implemented.",
                "builtin", "manual/built-in-functions.md#numeric-and-structural-output"},
            {"Degree", "One degree, equal to Pi/180 radians.", "Constants",
                {"Degree"}, {"N[Degree] -> 0.017453"},
                "Symbolic Degree remains exact as a named constant until numeric evaluation is requested.",
                "No unit system or dimensional analysis is implemented.",
                "builtin", "manual/built-in-functions.md#trigonometric-and-hyperbolic-functions"},
        };
        return entries;
    }

    inline const HelpEntry* find_help_entry(const std::string& name) {
        for (const auto& entry : get_help_entries()) {
            if (entry.name == name) {
                return &entry;
            }
        }
        return nullptr;
    }

}
